### PR TITLE
Make openvswitch.org mobile friendly

### PR DESCRIPTION
**Pull request by stephenfin**
When trying to integrate the Sphinx docs into the openvswitch.org theme, I noticed that the general design could do with a little "responsitivity". This resolves one of the TODOs in the file formerly known as `_TODO`.

### CODE REVIEW

**Comment by blp** [comment]
My apologies that I didn't see this earlier.  Is it still relevant?  Is there a reason to make it a pull request instead of emailing?

**Comment by stephenfin** [comment]
No problem. Yeah, it still applies. I was pretty sure that pull requests were the only way to submit changes for openvswitch.org (as opposed to Open vSwitch itself)

**Comment by blp** [comment]
I guess I wasn't paying attention properly, so I didn't notice that this was a website pull request but only that it had a merge conflict.

Anyway, please resolve the conflict and then resubmit it one or another, either a PR or emails, and then I'll take care of it.

Thank you for working on the website!

**Comment by stephenfin** [comment]
Done and done.

**Comment by blp** [comment]
Merged.

**Comment by blp** [comment]
I had to unmerge this because it left the website looking terrible. See http://benpfaff.org/~blp/private/SS2lphsn/Screenshot%20-%2012142016%20-%2009:29:08%20AM.png

**Comment by stephenfin** [comment]
I've no idea what happened there. It worked fine locally. Let me retry that

**Pull request merged**
